### ISSUE TITLE
Prompt not working with Deno 1.0.1

### ISSUE THREAD

**Issue by felixblaschke** [c4spar/deno-cliffy#24]
Given the following code derived from your examples:
```ts
import { Input } from "https://deno.land/x/cliffy/prompt.ts";

const name: string = await Input.prompt(`What's your name?`);
console.log("Your name is", name);
```

will come up with three errors:

```
error: TS2322 [ERROR]: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
const name: string = await Input.prompt(`What's your name?`);
      ~~~~
    at file:///C:/Users/felix/dev/deno/test.ts:3:7

TS2339 [ERROR]: Property 'setRaw' does not exist on type 'typeof Deno'.
    Deno.setRaw( 0, true );
         ~~~~~~
    at https://deno.land/x/cliffy/packages/prompt/lib/read-line.ts:14:10

TS2339 [ERROR]: Property 'setRaw' does not exist on type 'typeof Deno'.
    Deno.setRaw( 0, false );
         ~~~~~~
    at https://deno.land/x/cliffy/packages/prompt/lib/read-line.ts:16:10

Found 3 errors.
```

I used deno 1.0.1 on Windows.

**Comment by c4spar** [comment]
Hi @felixblaschke,

thx for the issue! The problem with `.setRaw()` is it is marked as unstable. So you have to run deno with the `--unstable` flag: `deno run --unstable <file-name>`.

And the return type from the `Input.prompt()` method is `string | undefined`. It's wrong in the documentation but i want to changes the return type and remove the `undefined` type soon.

Here is a working example:

```typescript
#!/usr/bin/env -S deno run --unstable

import { Input } from "https://deno.land/x/cliffy/prompt.ts";

const name: string | undefined = await Input.prompt(`What's your name?`);
console.log("Your name is", name);
```

**Comment by c4spar** [comment]
I have created a new issue for the return type #25.

**Comment by felixblaschke** [comment]
Thank you.
